name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Select build type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle


    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build and Sign APK
      run: |
        VERSION_CODE=${{ github.run_number }}
        VERSION_NAME=1.0.${{ github.run_number }}
        if [[ "${{ github.event.inputs.buildType }}" == "release" ]]; then
          echo "$KEYSTORE_BASE64" | base64 -d > /tmp/keystore.jks
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=/tmp/keystore.jks \
            -Pandroid.injected.signing.store.password="$KEYSTORE_PASSWORD" \
            -Pandroid.injected.signing.key.alias="$KEY_ALIAS" \
            -Pandroid.injected.signing.key.password="$KEY_PASSWORD" \
            -PversionCode=$VERSION_CODE \
            -PversionName=$VERSION_NAME;
        else
          ./gradlew assembleDebug -PversionCode=$VERSION_CODE -PversionName=$VERSION_NAME;
        fi
      env:
        GRADLE_BUILD_TYPE: ${{ github.event.inputs.buildType }}
        KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Rename APK to include version
      run: |
        VERSION_NAME=1.0.${{ github.run_number }}
        BUILD_TYPE=${{ github.event.inputs.buildType }}
        BUILD_TYPE=${BUILD_TYPE:-debug}
        cd app/build/outputs/apk/$BUILD_TYPE
        for f in *.apk; do
          mv "$f" "${f%.apk}-v$VERSION_NAME.apk"
        done

    - name: Upload APK as build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.buildType }}-build
        path: app/build/outputs/apk/${{ github.event.inputs.buildType }}/
